#!/usr/bin/env bash
# The 5 to 9 — mechanics demo: end-to-end shift on a throwaway repo.
#
# WHAT THIS IS: A reproducible offline demonstration of the shift lifecycle.
# The "agent" is a SCRIPTED COOK — deterministic bash, not a frontier model.
# It proves the mechanics: setup-shift → Stop-hook block → night-shift drains
# backlog (QUEUE-EMPTY) → clock-out prints the shift report. Nothing here
# requires network access or a live LLM.
#
# OUTPUT: docs/sample-shift-report.md (committed artifact; honest about its origin).
#
# usage: demo-shift.sh [--output PATH]
#   --output PATH   write the report to PATH (default: docs/sample-shift-report.md)
set -uo pipefail

F9_HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
F9_ROOT="$(cd "$F9_HERE/.." && pwd)"

output="$F9_ROOT/docs/sample-shift-report.md"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) output="$2"; shift 2;;
    --output=*) output="${1#*=}"; shift;;
    *) shift;;
  esac
done

if ! command -v bd >/dev/null 2>&1; then
  printf '[demo-shift] bd not installed — demo requires bd\n' >&2
  exit 1
fi

# ── Throwaway repo setup ──────────────────────────────────────────────────────
TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP" 2>/dev/null || true; }
trap cleanup EXIT

export CLAUDE_PROJECT_DIR="$TMP"
export CLAUDE_PLUGIN_ROOT="$F9_ROOT"
unset BEADS_DIR

( cd "$TMP" && git init -q 2>/dev/null && \
  git config user.email "demo@the-5-to-9.local" 2>/dev/null && \
  git config user.name "Demo Shift" 2>/dev/null ) || true

# Seed beads in the throwaway repo.
( cd "$TMP" && bd init >/dev/null 2>&1 ) || { printf '[demo-shift] bd init failed\n' >&2; exit 1; }
export BEADS_DIR="$TMP/.beads"
( cd "$TMP" && \
  bd create -t task "add greeting helper (scripted-cook demo bead 1)" >/dev/null 2>&1 && \
  bd create -t task "add farewell helper (scripted-cook demo bead 2)" >/dev/null 2>&1 && \
  bd create -t task "add version constant (scripted-cook demo bead 3)" >/dev/null 2>&1 ) || true

state_dir="$TMP/.claude/five-to-nine"
state_file="$state_dir/shift.local.md"

# ── Capture buffer ────────────────────────────────────────────────────────────
LOG="$TMP/demo.log"

{
  printf '<!-- MECHANICS DEMO: scripted cook, not a frontier-model run. -->\n\n'
  printf '# Sample Shift Report — The 5 to 9 Mechanics Demo\n\n'
  printf 'Generated by `scripts/demo-shift.sh` on %s.\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '> **What this is:** A reproducible offline demonstration of the shift lifecycle.\n'
  printf '> The agent is a **scripted cook** (deterministic bash) — not a frontier-model run.\n'
  printf '> It proves the mechanics work end-to-end, not the crew'"'"'s intelligence.\n\n'
  printf '%s\n\n' '---'
} > "$LOG"

# ── Phase 1: setup-shift ──────────────────────────────────────────────────────
{
  printf '## Phase 1: setup-shift\n\n```\n'
  bash "$F9_ROOT/scripts/setup-shift.sh" --no-branch "demo: prove end-to-end shift mechanics" 2>&1
  printf '```\n\n'
} >> "$LOG"

# ── Phase 2: Stop-hook — no-op (no active shift → silent) ────────────────────
{
  printf '## Phase 2: Stop-hook with no active shift (no-clobber)\n\n```\n'
  mv "$state_file" "$state_file.bak" 2>/dev/null || true
  noop="$(printf '{}' | bash "$F9_ROOT/hooks/shift-loop.sh" 2>/dev/null)"
  if [[ -z "$noop" ]]; then
    printf '(no output — hook is silent, allows Claude to stop)\n'
  else
    printf '%s\n' "$noop"
  fi
  mv "$state_file.bak" "$state_file" 2>/dev/null || true
  printf '```\n\n'
} >> "$LOG"

# ── Phase 3: Stop-hook — blocks (ready work present) ─────────────────────────
{
  printf '## Phase 3: Stop-hook with ready work (blocks the loop)\n\n```\n'
  blk="$(printf '{}' | bash "$F9_ROOT/hooks/shift-loop.sh" 2>/dev/null)"
  if printf '%s' "$blk" | grep -q '"decision":"block"'; then
    printf '%s\n' "$blk" | head -c 300
    printf '\n... (truncated — key field: "decision":"block")\n'
  else
    printf '%s\n' "$blk"
  fi
  printf '```\n\n'
} >> "$LOG"

# ── Phase 4: night-shift drains backlog with scripted cook ───────────────────
#
# SCRIPTED COOK: each iteration claims a bead, creates a tiny bash file (a real
# change), runs bash -n on it (the mechanical gate), commits, and bd-closes.
# This is what a real LLM Dealer would do — the cook just does it deterministically.
#
SCRIPTED_COOK='
set -e
id=$(bd ready --claim --json 2>/dev/null | jq -r ".[0].id // empty" 2>/dev/null)
[ -z "$id" ] && exit 0
title=$(bd show "$id" 2>/dev/null | awk "/^Title:/{sub(/^Title:[[:space:]]*/,\"\"); print; exit}")
[ -z "$title" ] && title="$id"
# Make a real file change: a tiny bash snippet named after the bead id.
fname="lib/bead-${id}.sh"
mkdir -p "$(dirname "$CLAUDE_PROJECT_DIR/$fname")"
printf "#!/usr/bin/env bash\n# Auto-generated by scripted cook for bead: %s\n# %s\nbead_id() { printf '"'"'%s\n'"'"' \"$id\"; }\n" "$id" "$title" > "$CLAUDE_PROJECT_DIR/$fname"
# Mechanical gate: bash -n (syntax check).
bash -n "$CLAUDE_PROJECT_DIR/$fname"
# Commit.
( cd "$CLAUDE_PROJECT_DIR" && git add "$fname" 2>/dev/null && git commit -m "feat: $title [scripted-cook demo]" --allow-empty 2>/dev/null ) || true
# bd close.
bd close "$id" >/dev/null 2>&1
printf "BEAD-DONE: %s — %s\n" "$id" "$title"
'

{
  printf '## Phase 4: night-shift drain (scripted cook)\n\n'
  printf 'The scripted cook claims each bead, creates a bash file, runs `bash -n` (gate), commits, and closes.\n\n```\n'
  export FIVE_TO_NINE_AGENT_CMD="$SCRIPTED_COOK"
  ( cd "$TMP" && bash "$F9_ROOT/scripts/night-shift.sh" --max-iterations 10 ) 2>&1
  printf '```\n\n'
} >> "$LOG"

# ── Phase 5: clock-out ────────────────────────────────────────────────────────
{
  printf '## Phase 5: clock-out shift report\n\n```\n'
  bash "$F9_ROOT/scripts/clock-out.sh" 2>&1
  printf '```\n\n'
} >> "$LOG"

# ── Verify QUEUE-EMPTY and Shift closed are present ──────────────────────────
if ! grep -q 'QUEUE-EMPTY' "$LOG"; then
  printf '[demo-shift] ERROR: night-shift did not reach QUEUE-EMPTY\n' >&2
  exit 1
fi
if ! grep -q 'Shift closed' "$LOG"; then
  printf '[demo-shift] ERROR: clock-out did not print shift summary\n' >&2
  exit 1
fi

# ── Append bead inventory ─────────────────────────────────────────────────────
{
  printf '%s\n\n## Bead inventory after the shift\n\n```\n' '---'
  ( cd "$TMP" && bd count --status closed 2>/dev/null && printf 'bead(s) closed\n' ) 2>&1 || true
  ( cd "$TMP" && bd ready --json 2>/dev/null | jq 'length' 2>/dev/null | xargs -I{} printf '{} bead(s) still ready\n' ) 2>/dev/null || true
  printf '```\n\n'
  printf '%s\n\n' '---'
  printf '*This report was generated offline by `scripts/demo-shift.sh`.*\n'
  printf '*The scripted cook is deterministic bash. No LLM was invoked.*\n'
} >> "$LOG"

# Write to the final output path.
mkdir -p "$(dirname "$output")"
cp "$LOG" "$output"
printf '[demo-shift] report written to %s\n' "$output" >&2
